# Generated by Django 5.2.4 on 2026-05-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='submittedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.CharField(max_length=100)),
                ('completionTime', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('timingClassification', models.CharField(default='unknown', max_length=20)),
                ('supecious_timing_flag', models.BooleanField(default=False)),
                ('timing_risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
