# Generated by Django 5.2.4 on 2026-06-02 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectfraud', '0002_submittedtask_tasktype'),
        ('service', '0025_alter_jobshistory_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_duplicate_screenshot', models.BooleanField(default=False)),
                ('completion_duration', models.FloatField(default=0)),
                ('timing_risk_score', models.IntegerField(default=0)),
                ('timing_classification', models.CharField(blank=True, max_length=50)),
                ('std_dev', models.FloatField(default=0)),
                ('z_score', models.FloatField(default=0)),
                ('population_score', models.IntegerField(default=0)),
                ('timing_consistency_score', models.IntegerField(default=0)),
                ('validity_score', models.IntegerField(default=0)),
                ('logical_behavior_flag', models.BooleanField(default=False)),
                ('repetitive_behavior_flag', models.BooleanField(default=False)),
                ('overall_behavior_label', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('device_seller_count', models.IntegerField(default=1)),
                ('ip_seller_count', models.IntegerField(default=1)),
                ('device_sharing_score', models.FloatField(default=0)),
                ('ip_reuse_score', models.FloatField(default=0)),
                ('device_sharing_label', models.CharField(blank=True, max_length=50)),
                ('ip_reuse_label', models.CharField(blank=True, max_length=50)),
                ('prediction', models.CharField(choices=[('FRAUD', 'Fraud'), ('LEGITIMATE', 'Legitimate')], default='LEGITIMATE', max_length=20)),
                ('fraud_probability', models.FloatField(default=0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('is_fraud', models.BooleanField(default=False)),
                ('fraud_reasons', models.JSONField(default=list)),
                ('suspicious_signals', models.JSONField(default=list)),
                ('seller_type', models.CharField(blank=True, max_length=20)),
                ('seller_age_days', models.IntegerField(default=0)),
                ('seller_trust_score', models.FloatField(default=0)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_analysis', to='service.jobshistory')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_analyses', to='service.sellerprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_analyses', to='service.buyertasks')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.DeleteModel(
            name='submittedTask',
        ),
        migrations.AddIndex(
            model_name='fraudanalysisresult',
            index=models.Index(fields=['seller', 'is_fraud'], name='detectfraud_seller__eef20e_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudanalysisresult',
            index=models.Index(fields=['task', 'analyzed_at'], name='detectfraud_task_id_3a858d_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudanalysisresult',
            index=models.Index(fields=['risk_level'], name='detectfraud_risk_le_7671fe_idx'),
        ),
    ]
