# Generated by Django 5.2.4 on 2026-03-27 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_user_first_name_user_last_name_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('taskType', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('progressed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('goal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('pricePerAction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.buyerprofile')),
            ],
        ),
    ]
