# Generated by Django 5.2.8 on 2026-04-06 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_buyertasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyertasks',
            name='title',
            field=models.CharField(default='New Task', max_length=100),
        ),
        migrations.AlterField(
            model_name='buyertasks',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='service.buyerprofile'),
        ),
    ]
