# Generated by Django 5.2.8 on 2026-04-06 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_buyertasks_title_alter_buyertasks_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyertasks',
            name='startDate',
        ),
    ]
