# Generated by Django 5.2.4 on 2026-05-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_testaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testaccount',
            old_name='user_Id',
            new_name='user_id',
        ),
    ]
