# Generated by Django 5.2.8 on 2026-04-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_buyertasks_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyertasks',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
