# Generated by Django 5.2.8 on 2026-04-06 03:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_buyertasks_enddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyertasks',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='buyertasks',
            name='pricePerAction',
        ),
        migrations.AddField(
            model_name='buyertasks',
            name='startDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
