# Generated by Django 5.2.8 on 2026-04-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_buyertasks_enddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyertasks',
            name='startDate',
        ),
        migrations.AddField(
            model_name='buyertasks',
            name='reviewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
