# Generated by Django 5.2.8 on 2026-04-15 04:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_remove_buyertasks_startdate_buyertasks_reviewed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyertasks',
            name='approval_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='buyertasks',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyertasks',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyertasks',
            name='pricePerAction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='buyertasks',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='buyertasks',
            name='startDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
