# Generated by Django 5.2.8 on 2026-04-15 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_buyertasks_approval_status_buyertasks_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyertasks',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='buyertasks',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='buyertasks',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='buyertasks',
            name='reviewed_date',
        ),
        migrations.RemoveField(
            model_name='buyertasks',
            name='title',
        ),
        migrations.AlterField(
            model_name='buyertasks',
            name='approval_status',
            field=models.CharField(choices=[('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='awaiting_approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='buyertasks',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.buyerprofile'),
        ),
    ]
