# Generated by Django 5.2.8 on 2026-04-15 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_remove_buyertasks_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyertasks',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyertasks',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyertasks',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='buyertasks',
            name='reviewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyertasks',
            name='title',
            field=models.CharField(default='New Task', max_length=100),
        ),
        migrations.AlterField(
            model_name='buyertasks',
            name='approval_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='buyertasks',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='service.buyerprofile'),
        ),
    ]
