# Generated by Django 5.2.4 on 2026-05-31 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_jobshistory_proofimage_jobshistory_proofsha256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobshistory',
            name='proofImage',
        ),
        migrations.RemoveField(
            model_name='jobshistory',
            name='proofSha256',
        ),
    ]
