# Generated by Django 5.2.4 on 2026-05-31 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_user_seller_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='seller_type',
        ),
    ]
