# Generated by Django 5.2.4 on 2026-05-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_remove_user_seller_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobshistory',
            name='proofPhash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
