# Generated by Django 5.2.4 on 2026-06-01 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_jobshistory_proofphash'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobshistory',
            unique_together={('seller', 'task')},
        ),
    ]
