"""
Django settings for BackEnd project.

Generated by 'django-admin startproject' using Django 5.2.4.
"""

import os
from pathlib import Path



BASE_DIR = Path(__file__).resolve().parent.parent

ENV_FILE = BASE_DIR / ".env"
if ENV_FILE.exists():
    for line in ENV_FILE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))

SECRET_KEY = 'django-insecure-kibq^_(ud^&h3nni_v6oqi-ff(hqz79f#c8ka+@%b!2*ae%_76'

DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost","caddie-unlearned-author.ngrok-free.dev","preflight-museum-fence.ngrok-free.dev"]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    
]

CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOW_CREDENTIALS = True

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'service',
    'corsheaders',
    'mlservice',
    'social_auth',
    'rest_framework',
    'detectfraud',
 
]


CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'ngrok-skip-browser-warning',  # ← add this
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BackEnd.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "https://caddie-unlearned-author.ngrok-free.dev",
    "https://preflight-museum-fence.ngrok-free.dev"
]

WSGI_APPLICATION = 'BackEnd.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'engageX',
        'USER': 'root',
        'PASSWORD': 'horserider12',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'service.User'

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_NAME = "sessionid"
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SAMESITE = 'Lax'


EASYPAISA_STORE_ID = os.getenv("EASYPAISA_STORE_ID", "43")
EASYPAISA_USERNAME = os.getenv("EASYPAISA_USERNAME", "")
EASYPAISA_PASSWORD = os.getenv("EASYPAISA_PASSWORD", "")
EASYPAISA_ACCOUNT_NUM = os.getenv("EASYPAISA_ACCOUNT_NUM", "654123987")
EASYPAISA_MA_URL = os.getenv(
    "EASYPAISA_MA_URL",
    "https://easypaystg.easypaisa.com.pk/easypay-service/rest/v4/initiate-ma-transaction",
)
EASYPAISA_INQUIRE_URL = os.getenv(
    "EASYPAISA_INQUIRE_URL",
    "https://easypaystg.easypaisa.com.pk/easypay-service/rest/v4/inquire-transaction",
)
EASYPAISA_MOCK_PAYMENTS = os.getenv("EASYPAISA_MOCK_PAYMENTS", "false").lower() == "true"


# settings.py
FACEBOOK_CLIENT_ID = "1476377807463568"
FACEBOOK_CLIENT_SECRET = "3044d13c8f818b9fb663012762641466"
INSTAGRAM_CLIENT_ID = "2788596471498218"
INSTAGRAM_CLIENT_SECRET = "8b1c84783454d65c89d0a4f2bb4e9adf"
TWITTER_CLIENT_ID = "dXVPWEVhSDBUdEFzQ2p2dFA0dEY6MTpjaQ"
TWITTER_CLIENT_SECRET = "kltfXp7vD5wZq6p_23yJPS7fuPQ-1rAClDPfEVimQE0HH-p278"
YOUTUBE_CLIENT_ID = "553758333721-a0048757abn3s6kdosdr0sucr596kanh.apps.googleusercontent.com"
YOUTUBE_CLIENT_SECRET = "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"


FACEBOOK_REDIRECT_URI = "https://caddie-unlearned-author.ngrok-free.dev/oauth/facebook/callback/"
INSTAGRAM_REDIRECT_URI = "https://caddie-unlearned-author.ngrok-free.dev/oauth/instagram/callback/"
TWITTER_REDIRECT_URI = "https://caddie-unlearned-author.ngrok-free.dev/oauth/twitter/callback/"
YOUTUBE_REDIRECT_URI = "https://caddie-unlearned-author.ngrok-free.dev/oauth/youtube/callback/"






from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
}

import os

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")