# Generated by Django 5.2.4 on 2026-05-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectfraud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedtask',
            name='taskType',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
