# Generated by Django 5.2.4 on 2026-04-29 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_socialaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialaccount',
            name='user',
        ),
    ]
