# Generated by Django 5.2.4 on 2026-05-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_rename_user_id_testaccount_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='sellerId',
            field=models.IntegerField(default=0),
        ),
    ]
