# Generated by Django 5.2.13 on 2026-05-11 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_socialaccount_sellerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='unethical_reports',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('escrow_in', 'Escrow In'), ('escrow_release', 'Escrow Release'), ('refund', 'Refund'), ('penalty', 'Penalty'), ('withdraw', 'Withdraw')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('holding', 'Holding'), ('released', 'Released'), ('refunded', 'Refunded')], default='holding', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_payments', to='service.buyerprofile')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_earnings', to='service.sellerprofile')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_wallet', to='service.buyertasks')),
            ],
        ),
    ]
