# Generated by Django 5.2.13 on 2026-05-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_sellerprofile_unethical_reports_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobshistory',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobshistory',
            name='proofUrl',
            field=models.URLField(blank=True),
        ),
    ]
