# Generated by Django 5.2.13 on 2026-05-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_ensure_ratingindexes_table'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jobshistory',
            constraint=models.UniqueConstraint(fields=('seller', 'task'), name='unique_seller_task_assignment'),
        ),
    ]
