# Generated by Django 5.2.4 on 2026-05-30 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_jobshistory_unique_seller_task_assignment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobshistory',
            name='unique_seller_task_assignment',
        ),
    ]
