# Generated by Django 5.2.13 on 2026-05-30 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_easypaisatransaction_sellerwithdrawalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='ratings',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
