# Generated by Django 5.2.4 on 2026-05-31 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_remove_jobshistory_unique_seller_task_assignment'),
        ('service', '0014_alter_sellerprofile_ratings'),
    ]

    operations = [
    ]
