# Generated by Django 5.2.4 on 2026-05-31 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_merge_20260531_1518'),
        ('service', '0015_sellerbehaviorlog'),
    ]

    operations = [
    ]
