# Generated by Django 5.2.4 on 2026-05-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_remove_jobshistory_proofimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobshistory',
            name='proofImage',
            field=models.ImageField(blank=True, null=True, upload_to='proof_screenshots/'),
        ),
        migrations.AddField(
            model_name='jobshistory',
            name='proofSha256',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
