# Generated by Django 5.2.4 on 2026-05-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_jobshistory_proofimage_jobshistory_proofsha256'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='trust_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
    ]
