# Generated by Django 5.2.4 on 2026-05-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_sellerprofile_trust_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller_type',
            field=models.CharField(default='new', max_length=20),
        ),
    ]
