# Generated by Django 5.2.4 on 2026-06-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_alter_jobshistory_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobshistory',
            unique_together=set(),
        ),
    ]
