# Generated by Django 5.2.4 on 2026-06-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_alter_jobshistory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobshistory',
            name='fraud_id',
            field=models.IntegerField(default=0),
        ),
    ]
