# Generated by Django 5.2.4 on 2026-06-03 23:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_jobshistory_fraud_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobshistory',
            name='lock_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='last_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='queue_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='JobRatingQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('total_quota', models.PositiveIntegerField(default=0)),
                ('assigned_count', models.PositiveIntegerField(default=0)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_quotas', to='service.buyertasks')),
            ],
        ),
        migrations.AddField(
            model_name='jobshistory',
            name='quota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='service.jobratingquota'),
        ),
        migrations.AddIndex(
            model_name='jobshistory',
            index=models.Index(fields=['seller', 'status'], name='service_job_seller__ea3083_idx'),
        ),
        migrations.AddIndex(
            model_name='jobshistory',
            index=models.Index(fields=['task', 'status'], name='service_job_task_id_638645_idx'),
        ),
        migrations.AddIndex(
            model_name='jobshistory',
            index=models.Index(fields=['quota', 'status'], name='service_job_quota_i_d3af9b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobratingquota',
            index=models.Index(fields=['rating', 'created_at'], name='service_job_rating_920b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='jobratingquota',
            index=models.Index(fields=['task', 'rating'], name='service_job_task_id_5a30be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobratingquota',
            unique_together={('task', 'rating')},
        ),
    ]
