# Generated by Django 5.2.4 on 2026-06-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_jobshistory_lock_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobratingquota',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')]),
        ),
    ]
